export const DINE_MENU_TAB_BUTTON_NAMES = {
    BREAK_FAST: 'BREAK_FAST',
    LUNCH: 'LUNCH',
    DINNER: 'DINNER'
}

export const CHECKOUT_MENU_TAB_BUTTON_NAMES = {
    NEW_CUSTOMER: 'NEW_CUSTOMER',
    EXISTING_CUSTOMER: 'EXISTING_CUSTOMER',
}

export const GALLERY_MENU_TAB_BUTTON_NAMES = {
    SPACES : 'SPACES',
    ACTIVITIES : 'ACTIVITIES',
    POOLS : 'POOLS',
    RESTAURANTS : 'RESTAURANTS',
    SPA : 'SPA',
    REVIEWS : 'REVIEWS'
}

